name: commit_ai
description: Commits ai generator
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0

  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0

  flutter_localizations:
    sdk: flutter

  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  go_router: ^14.6.3
  intl: ^0.19.0
  path: ^1.9.0
  timeago: ^3.7.0
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  fpdart: ^1.1.1
  git: ^2.3.1
  firebase_core: ^3.12.1
  firebase_vertexai: ^1.4.0

  sembast: ^3.8.4
  sembast_web: ^2.4.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15

  flutter_launcher_icons: ^0.14.3

  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  freezed: ^3.0.2
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
  test: ^1.16.0

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  macos:
    generate: true
    image_path: "assets/icon.png"
