// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr3MB1QJWS2y3PasF-Fc-flLs388k9wYU',
    appId: '1:977584641309:web:027067849ec812b962bdf4',
    messagingSenderId: '977584641309',
    projectId: 'charla-vertex',
    authDomain: 'charla-vertex.firebaseapp.com',
    storageBucket: 'charla-vertex.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg_pMVn5fQUOBFqZtRIj7fi975d1fv-JM',
    appId: '1:977584641309:android:7a24ac1c0281f3be62bdf4',
    messagingSenderId: '977584641309',
    projectId: 'charla-vertex',
    storageBucket: 'charla-vertex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAexyiYiNt_RtrHT2aFwse2xysJSuNMPkk',
    appId: '1:977584641309:ios:8ab8739478afce5862bdf4',
    messagingSenderId: '977584641309',
    projectId: 'charla-vertex',
    storageBucket: 'charla-vertex.firebasestorage.app',
    iosBundleId: 'gitcommit.online.commit-ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAexyiYiNt_RtrHT2aFwse2xysJSuNMPkk',
    appId: '1:977584641309:ios:17c8848e7fffaaf562bdf4',
    messagingSenderId: '977584641309',
    projectId: 'charla-vertex',
    storageBucket: 'charla-vertex.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr3MB1QJWS2y3PasF-Fc-flLs388k9wYU',
    appId: '1:977584641309:web:23199301648651cb62bdf4',
    messagingSenderId: '977584641309',
    projectId: 'charla-vertex',
    authDomain: 'charla-vertex.firebaseapp.com',
    storageBucket: 'charla-vertex.firebasestorage.app',
  );
}
